### ISSUE TITLE
Error fresh clone

### ISSUE THREAD

**Issue by jnor** [enormandeau/meditation-timer#10]
./meditation_timer.py -h                                                                                                                   master
  File "./meditation_timer.py", line 42
    print " Waited:", pretty_time(delta)
                   ^
SyntaxError: invalid syntax

**Comment by enormandeau** [comment]
`meditation_timer` was developed for Python 2. You must be using Python 3. If you want to fix the errors with Python 3, I will be happy to merge your changes.

**Comment by jnor** [comment]
Dont have time atm but thanks for clearing that up :-))

**Comment by enormandeau** [comment]
Hi jnor. It now works with Python3 but the sound doesn't work :P I'll have to fix this.
