### ISSUE TITLE
Bell chime intervals

### ISSUE THREAD

**Issue by fn-ix** [enormandeau/meditation-timer#11]
Hello!

I would like to request the ability to set the duration between the bell strikes: this helps make the bells sound more realistic as in reality a bell is often struck while the sound from the previous strike is still subsiding. Currently, the interval seems to be hardcoded, so the effect depends on the length of the bell sound which, in case the sound is long, is cut off unnaturally as the playback get suddenly interrupted and replaced by a new strike. 

Additionally, it would also be nice if it was possible to have several concurrent bell sound streams, so that when a new strike is made, the abating sound from the old one can still be heard, making the strikes sound considerably more natural.

EDIT: Apparently, this seems to especially be a problem with pygame, which sometimes sounds choppy when playing a new sound. Replaced it with mpv which works much better, and is also supported on Windows and Mac. ;)

**Comment by enormandeau** [comment]
Meditation timer is an old project for which I do not have a lot of time for improvements. You say you "Replaced it with mpv which works much better"? Do you have the code so I can speed up testing?

**Comment by hfel** [comment]
Sure, I created a PR #14 .
